dict={'name':'pasu','age':20,'gender':'male'}
#print(dict['name'])
#print(dict['age'])
#print(dict)
#dict['name']='nivi'
#dict['gender']='female'
#dict['college']='satybama'
#print(dict)
#del dict['age']
#print(dict)
#dict.clear()
#del dict
#print(dict)
dict1={'name':'nivi','age':20,'gender':'female'}
dict2={'name':'satish','age':20,'gender':'male'}
#print(Cmp(dict,dict2))
#print(len(dict))
#print(str(dict))
#dict3=dict.copy()
#print(dict3)
#seq=('name','gender')
#dict=dict.fromkeys(seq)
#print(dict)
#dict=dict.fromkeys(seq,10)
#print(dict)
#print(dict.__contains__('na'))
#print(dict.keys())
#print(dict.values())
#print(dict.setdefault('name',None))
