str=set(['1','2','3','2','3'])
str1={'2','1','5','3','2'}
print(str.union(str1))
print(str.intersection(str1))
print(str.issubset(str1))
print(str1.issubset(str))
print(str.difference(str1))
print(str1.difference(str))
print(str.symmetric_difference(str1))
str2=str.copy()
print(str2)
str.update('7')
print(str)
engineers = set(['John', 'Jane', 'Jack', 'Janice',])
programmers = set(['Jack', 'Sam', 'Susan', 'Janice'])
engineers.update(programmers)
print(engineers)